import scrapy
import json
import MySQLdb
from scrapy.selector import Selector
from scrapy.http import HtmlResponse

class RankingSpider(scrapy.Spider):
    name = "ranking"

    def start_requests(self):
        codes = [
            'AFG',
            'ALB',
            'GER',
            'AND',
            'ANG',
            'AIA',
            'ATG',
            'KSA',
            'ALG',
            'ARG',
            'ARM',
            'ARU',
            'MKD',
            'AUS',
            'AUT',
            'AZE',
            'BAH',
            'BHR',
            'BAN',
            'BRB',
            'BEL',
            'BLZ',
            'BEN',
            'BER',
            'BLR',
            'BOL',
            'BIH',
            'BOT',
            'BRA',
            'BRU',
            'BUL',
            'BFA',
            'BDI',
            'BHU',
            'CPV',
            'CAM',
            'CMR',
            'CAN',
            'CHA',
            'CHI',
            'TPE',
            'CYP',
            'COL',
            'COM',
            'CGO',
            'CIV',
            'CRC',
            'CRO',
            'CUB',
            'CUW',
            'DEN',
            'DMA',
            'ECU',
            'USA',
            'EGY',
            'SLV',
            'UAE',
            'ERI',
            'SCO',
            'SVK',
            'SVN',
            'ESP',
            'EST',
            'ETH',
            'PHI',
            'FIN',
            'FIJ',
            'FRA',
            'GAB',
            'WAL',
            'GAM',
            'GEO',
            'GHA',
            'GIB',
            'GRN',
            'GRE',
            'GUM',
            'GUA',
            'GUI',
            'EQG',
            'GNB',
            'GUY',
            'HAI',
            'HON',
            'HKG',
            'HUN',
            'IND',
            'IDN',
            'ENG',
            'IRQ',
            'IRN',
            'NIR',
            'ISL',
            'CAY',
            'COK',
            'FRO',
            'SOL',
            'VGB',
            'VIR',
            'ISR',
            'ITA',
            'JAM',
            'JPN',
            'JOR',
            'KAZ',
            'KEN',
            'KGZ',
            'KVX',
            'KUW',
            'LAO',
            'LES',
            'LVA',
            'LIB',
            'LBR',
            'LBY',
            'LIE',
            'LTU',
            'LUX',
            'MAC',
            'MAD',
            'MAS',
            'MWI',
            'MDV',
            'MLI',
            'MLT',
            'MAR',
            'MRI',
            'MTN',
            'MEX',
            'MDA',
            'MNG',
            'MNE',
            'MSR',
            'MOZ',
            'MYA',
            'NAM',
            'NEP',
            'NCA',
            'NIG',
            'NGA',
            'NOR',
            'NCL',
            'NZL',
            'OMA',
            'NED',
            'PAK',
            'PLE',
            'PAN',
            'PNG',
            'PAR',
            'PER',
            'POL',
            'POR',
            'PUR',
            'QAT',
            'COD',
            'PRK',
            'CTA',
            'CZE',
            'KOR',
            'IRL',
            'DOM',
            'CHN',
            'RWA',
            'ROU',
            'RUS',
            'SAM',
            'ASA',
            'SKN',
            'SMR',
            'VIN',
            'LCA',
            'STP',
            'SEN',
            'SRB',
            'SEY',
            'SLE',
            'SIN',
            'SYR',
            'SOM',
            'SRI',
            'SWZ',
            'RSA',
            'SDN',
            'SSD',
            'SWE',
            'SUI',
            'SUR',
            'TAH',
            'THA',
            'TAN',
            'TJK',
            'TLS',
            'TOG',
            'TGA',
            'TRI',
            'TUN',
            'TCA',
            'TKM',
            'TUR',
            'UKR',
            'UGA',
            'URU',
            'UZB',
            'VAN',
            'VEN',
            'VIE',
            'YEM',
            'DJI',
            'ZAM',
            'ZIM',

        ]
        for code in codes:
            yield scrapy.Request(url='http://es.fifa.com/common/fifa-world-ranking/ma='+code+'/_history.js', meta={'code': code},  callback=self.parse)

    def parse(self, response):

        db = MySQLdb.connect(
            host="localhost",
            user="root",
            passwd="",
            db="dtdata"
        )
        cur = db.cursor()

        puestos = json.loads(response.body_as_unicode())

        for puesto in puestos:
            sql = "INSERT INTO ranking_ranking (code, deliverydate, rankseq) VALUES ('{}', '{}', {})".format(response.meta['code'], puesto["deliverydate"],puesto["rankseq"])
            
            cur.execute(sql)
            db.commit()
            
            print sql

        db.close()